import type { Metadata } from "next";
import { Instrument_Sans } from "next/font/google";
import "@/app/globals.css";
import Image from "next/image";
import { Toaster } from "@/components/ui/toaster"

const inter = Instrument_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className={inter.className}>
      <div className="flex min-h-screen flex-col items-center justify-start mb-[60px]">
        <div className="md:mb-[51px] md:pt-[150px] p-[32px] w-[100%] md:w-[476px]">
          <Image
            src="/logo.svg"
            alt="devlink Logo"
            className="cursor-pointer md:m-auto"
            width={182}
            height={40}
            priority
          />
        </div>

        {children}
      </div>
      <Toaster />
    </div>
  );
}
